env:
  global:
    - GAE_SDK: /home/travis/build/incognitoorg/expenseshare/vendors/appengine-java-sdk-1.9.4
    
#language: java

before_install:
  - wget https://storage.googleapis.com/appengine-sdks/featured/appengine-java-sdk-1.9.4.zip  -nv
  - wget https://www.dropbox.com/s/q69hrvjxv32b828/.appcfg_oauth2_tokens_java  -nv
  - unzip -qd vendors appengine-java-sdk-1.9.4.zip
  
before_script:
  - npm install -g grunt-cli
  - npm install>/dev/null
  - grunt -version
 
script : 
 - ant compile
 - grunt qa